version: "3.9"

services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: foodadmin
      POSTGRES_PASSWORD: StrongP@ssword123!
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  restaurant-service:
    build: ./restaurant-service
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - postgres
      - redis

  order-service:
    build: ./order-service
    ports:
      - "8001:8000"
    env_file: .env
    depends_on:
      - postgres

  delivery-service:
    build: ./delivery-service
    ports:
      - "8002:8000"
    env_file: .env
    depends_on:
      - postgres

volumes:
  pg_data: