name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  ACR_NAME: foodregistryartur.azurecr.io
  ORDER_APP: order_service
  DELIVERY_APP: delivery_service
  RESTAURANT_APP: restaurant_service
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure Container Registry Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_NAME }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push order_service
        run: |
          docker build -f order_service/Dockerfile -t $ACR_NAME/$ORDER_APP:$IMAGE_TAG -t $ACR_NAME/$ORDER_APP:latest .
          docker push $ACR_NAME/$ORDER_APP:$IMAGE_TAG
          docker push $ACR_NAME/$ORDER_APP:latest

      - name: Build and push delivery_service
        run: |
          docker build -f delivery_service/Dockerfile -t $ACR_NAME/$DELIVERY_APP:$IMAGE_TAG -t $ACR_NAME/$DELIVERY_APP:latest .
          docker push $ACR_NAME/$DELIVERY_APP:$IMAGE_TAG
          docker push $ACR_NAME/$DELIVERY_APP:latest

      - name: Build and push restaurant_service
        run: |
          docker build -f restaurant_service/Dockerfile -t $ACR_NAME/$RESTAURANT_APP:$IMAGE_TAG -t $ACR_NAME/$RESTAURANT_APP:latest .
          docker push $ACR_NAME/$RESTAURANT_APP:$IMAGE_TAG
          docker push $ACR_NAME/$RESTAURANT_APP:latest

      - name: Deploy order-service
        uses: azure/webapps-deploy@v2
        with:
          app-name: order-service-app
          images: ${{ env.ACR_NAME }}/${{ env.ORDER_APP }}:${{ env.IMAGE_TAG }}
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          SERVICE_BUS: ${{ secrets.SERVICE_BUS }}
          SERVICE_BUS_QUEUE_NAME: ${{ secrets.SERVICE_BUS_QUEUE_NAME }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}

      - name: Deploy delivery-service
        uses: azure/webapps-deploy@v2
        with:
          app-name: delivery-service-app
          images: ${{ env.ACR_NAME }}/${{ env.DELIVERY_APP }}:${{ env.IMAGE_TAG }}
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          SERVICE_BUS: ${{ secrets.SERVICE_BUS }}
          SERVICE_BUS_QUEUE_NAME: ${{ secrets.SERVICE_BUS_QUEUE_NAME }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}

      - name: Deploy restaurant-service
        uses: azure/webapps-deploy@v2
        with:
          app-name: restaurant-service-app
          images: ${{ env.ACR_NAME }}/${{ env.RESTAURANT_APP }}:${{ env.IMAGE_TAG }}
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
